"""Fresh AAC website baseline

Revision ID: 922533d3d862
Revises:
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "922533d3d862"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board_terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("current", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("start_year"),
    )
    op.create_table(
        "markers", sa.Column("key", sa.String(length=80), nullable=False), sa.PrimaryKeyConstraint("key")
    )
    op.create_table(
        "media",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("variants", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("pronouns", sa.String(length=60), nullable=False),
        sa.Column("discord", sa.String(length=100), nullable=False),
        sa.Column("can_drive", sa.Boolean(), nullable=True),
        sa.Column("student", sa.Boolean(), nullable=False),
        sa.Column("driving_preferences", sa.String(length=500), nullable=False),
        sa.Column("payout_method", sa.String(length=20), nullable=False),
        sa.Column("payout_destination", sa.String(length=200), nullable=False),
        sa.Column("payout_phone_suffix", sa.String(length=4), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "quarters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("budget", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("driver_cap", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("mpg", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint("state IN ('open','finalized','archived')"),
        sa.CheckConstraint("budget >= 0 AND driver_cap >= 0 AND mpg > 0"),
        sa.CheckConstraint("ends_on >= starts_on"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_limits",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("window", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity", sa.String(length=100), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_at"), "audit", ["at"], unique=False)
    op.create_table(
        "board_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("major", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.String(length=2000), nullable=False),
        sa.Column("memory", sa.String(length=1000), nullable=False),
        sa.Column("instagram", sa.String(length=300), nullable=False),
        sa.Column("photo_id", sa.String(length=64), nullable=True),
        sa.Column("palette", sa.String(length=30), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["media.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["board_terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_board_entries_term_id"), "board_entries", ["term_id"], unique=False)
    op.create_table(
        "driver_registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quarter_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("eligible_override", sa.Boolean(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quarter_id"],
            ["quarters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quarter_id", "member_id"),
    )
    op.create_index(
        op.f("ix_driver_registrations_member_id"), "driver_registrations", ["member_id"], unique=False
    )
    op.create_index(
        op.f("ix_driver_registrations_quarter_id"), "driver_registrations", ["quarter_id"], unique=False
    )
    op.create_table(
        "event_series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quarter_id", sa.Integer(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["quarter_id"],
            ["quarters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(op.f("ix_event_series_quarter_id"), "event_series", ["quarter_id"], unique=False)
    op.create_table(
        "identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("issuer", sa.String(length=200), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject"),
        sa.UniqueConstraint("member_id"),
    )
    op.create_table(
        "import_previews",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("specification", sa.JSON(), nullable=False),
        sa.Column("rows", sa.JSON(), nullable=False),
        sa.Column("issues", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("quarter_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("student", sa.Boolean(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.CheckConstraint("status IN ('general','pending','approved')"),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quarter_id"],
            ["quarters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "quarter_id"),
    )
    op.create_index(op.f("ix_memberships_member_id"), "memberships", ["member_id"], unique=False)
    op.create_index(op.f("ix_memberships_quarter_id"), "memberships", ["quarter_id"], unique=False)
    op.create_table(
        "officers",
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("member_id"),
    )
    op.create_table(
        "payouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quarter_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("reference", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quarter_id"],
            ["quarters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quarter_id", "member_id"),
    )
    op.create_index(op.f("ix_payouts_member_id"), "payouts", ["member_id"], unique=False)
    op.create_index(op.f("ix_payouts_quarter_id"), "payouts", ["quarter_id"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("make", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("color", sa.String(length=40), nullable=False),
        sa.Column("plate", sa.String(length=20), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("removed", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.CheckConstraint("capacity BETWEEN 1 AND 50"),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_member_id"), "vehicles", ["member_id"], unique=False)
    op.create_table(
        "dues_receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("membership_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("correction_of", sa.Integer(), nullable=True),
        sa.Column("voided", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["correction_of"],
            ["dues_receipts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dues_receipts_membership_id"), "dues_receipts", ["membership_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quarter_id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("original_date", sa.Date(), nullable=True),
        sa.Column("exception", sa.Boolean(), nullable=False),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("destination", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("signups_enabled", sa.Boolean(), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("arrival_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("departure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("return_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("packing", sa.JSON(), nullable=False),
        sa.Column("questions", sa.JSON(), nullable=False),
        sa.Column("photo_id", sa.String(length=64), nullable=True),
        sa.Column("miles", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("gas_price", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("rate_override", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=False),
        sa.Column("general_cards", sa.Integer(), nullable=False),
        sa.Column("paid_cards", sa.Integer(), nullable=False),
        sa.Column("completion", sa.JSON(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('regular','meeting','picnic','retreat')"),
        sa.CheckConstraint("state IN ('draft','published','completed','cancelled')"),
        sa.CheckConstraint("ends_at >= starts_at"),
        sa.CheckConstraint("miles >= 0 AND gas_price >= 0"),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["media.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quarter_id"],
            ["quarters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["event_series.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "original_date"),
    )
    op.create_index("ix_event_calendar", "events", ["starts_at", "ends_at", "state"], unique=False)
    op.create_index(op.f("ix_events_quarter_id"), "events", ["quarter_id"], unique=False)
    op.create_index(op.f("ix_events_series_id"), "events", ["series_id"], unique=False)
    op.create_table(
        "recaps",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("draft", sa.JSON(), nullable=False),
        sa.Column("published", sa.JSON(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "signups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=True),
        sa.Column("vehicle", sa.JSON(), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extended_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extension_reason", sa.String(length=500), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint("role IN ('ride','driver','own')"),
        sa.CheckConstraint("seats >= 0"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "member_id"),
    )
    op.create_index(op.f("ix_signups_event_id"), "signups", ["event_id"], unique=False)
    op.create_index(op.f("ix_signups_member_id"), "signups", ["member_id"], unique=False)
    op.create_table(
        "assignments",
        sa.Column("rider_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["signups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rider_id"],
            ["signups.id"],
        ),
        sa.PrimaryKeyConstraint("rider_id"),
    )
    op.create_index(op.f("ix_assignments_driver_id"), "assignments", ["driver_id"], unique=False)
    op.create_table(
        "attendance_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("signup_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signup_id"],
            ["signups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attendance_actions_event_id"), "attendance_actions", ["event_id"], unique=False)
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=10), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("signup_id", sa.Integer(), nullable=True),
        sa.Column("voided", sa.Boolean(), nullable=False),
        sa.CheckConstraint("number > 0"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signup_id"],
            ["signups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "category", "number"),
    )
    op.create_index(op.f("ix_cards_event_id"), "cards", ["event_id"], unique=False)
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("cost_override", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("arrival_signup_id", sa.Integer(), nullable=True),
        sa.Column("edited", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint("cost_override IS NULL OR cost_override >= 0"),
        sa.ForeignKeyConstraint(
            ["arrival_signup_id"],
            ["signups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "member_id"),
    )
    op.create_index(op.f("ix_trips_event_id"), "trips", ["event_id"], unique=False)
    op.create_index(op.f("ix_trips_member_id"), "trips", ["member_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trips_member_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_event_id"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_cards_event_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_attendance_actions_event_id"), table_name="attendance_actions")
    op.drop_table("attendance_actions")
    op.drop_index(op.f("ix_assignments_driver_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_signups_member_id"), table_name="signups")
    op.drop_index(op.f("ix_signups_event_id"), table_name="signups")
    op.drop_table("signups")
    op.drop_table("recaps")
    op.drop_index(op.f("ix_events_series_id"), table_name="events")
    op.drop_index(op.f("ix_events_quarter_id"), table_name="events")
    op.drop_index("ix_event_calendar", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_dues_receipts_membership_id"), table_name="dues_receipts")
    op.drop_table("dues_receipts")
    op.drop_index(op.f("ix_vehicles_member_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_payouts_quarter_id"), table_name="payouts")
    op.drop_index(op.f("ix_payouts_member_id"), table_name="payouts")
    op.drop_table("payouts")
    op.drop_table("officers")
    op.drop_index(op.f("ix_memberships_quarter_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_member_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_table("import_previews")
    op.drop_table("identities")
    op.drop_index(op.f("ix_event_series_quarter_id"), table_name="event_series")
    op.drop_table("event_series")
    op.drop_index(op.f("ix_driver_registrations_quarter_id"), table_name="driver_registrations")
    op.drop_index(op.f("ix_driver_registrations_member_id"), table_name="driver_registrations")
    op.drop_table("driver_registrations")
    op.drop_index(op.f("ix_board_entries_term_id"), table_name="board_entries")
    op.drop_table("board_entries")
    op.drop_index(op.f("ix_audit_at"), table_name="audit")
    op.drop_table("audit")
    op.drop_table("rate_limits")
    op.drop_table("quarters")
    op.drop_table("members")
    op.drop_table("media")
    op.drop_table("markers")
    op.drop_table("board_terms")
    # ### end Alembic commands ###
